name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup kind
        run: |
          make cluster/create
          make deploy
      - name: wait for available
        run: |
          make wait
      - name: Run test
        run: |
          make test
